version: "3"
networks:
  web-network:
services:
  docker-php-cli:
    build:
      context: ./php-cli
    ports:
    - "2222:22"
    tty: true
    volumes:
      - ./app:/var/www
    networks:
      - web-network
  docker-php-fpm:
    build:
      context: ./php-fpm
    tty: true
    volumes:
      - ./app:/var/www
    networks:
      - web-network
  docker-nginx:
    build:
      context: ./nginx
    tty: true
    volumes:
      - ./app:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - web-network

