version: "3.6"
networks:
  backend:
    driver: ${NETWORKS_DRIVER}
services:
### workspace ################################################
  workspace:
    build:
      context: .
      dockerfile: ./workspace/Dockerfile
      args:
        - WORKSPACE_PATH=${WORKSPACE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
        - NODE_VERSION=${NODE_VERSION}
    ports:
      - "${WORKSPACE_HOST_SSH_PORT}:22"
    tty: true
    volumes:
      - ${WORKSPACE_PATH_HOST}:${WORKSPACE_PATH_CONTAINER}
    networks:
      - backend
### nginx ################################################
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - WORKSPACE_PATH=${WORKSPACE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    tty: true
    volumes:
      - ${WORKSPACE_PATH_HOST}:${WORKSPACE_PATH_CONTAINER}
    networks:
      backend:
        aliases:
          - ${APP_HOST}
### PHP fpm ################################################
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - WORKSPACE_PATH=${WORKSPACE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
    tty: true
    volumes:
      - ${WORKSPACE_PATH_HOST}:${WORKSPACE_PATH_CONTAINER}
    networks:
      - backend
### MySQL ################################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
### Redis ################################################
  redis:
    build:
      context: ./redis
    volumes:
     - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
